#!/usr/bin/env bash
# =============================================================================
# Delegation Poker frontend — fetch runtime config from AWS SSM into an nginx
# snippet (set $poker_* ...) that the vhost includes and injects into index.html.
#
# Run by poker-frontend-runtime-fetch.service (oneshot) at boot + on deploy.
# Reads /poker-frontend/prod/* (eu-west-1) via the EC2 instance role. The config
# is PUBLIC (served to the browser) → SSM String only, never a secret.
# §3.10: runs as root, installed to /usr/local/sbin from the committed git blob.
# =============================================================================
set -euo pipefail

SSM_PREFIX="${POKER_FRONTEND_SSM_PREFIX:-/poker-frontend/prod}"
AWS_REGION="${AWS_REGION:-eu-west-1}"
OUT_FILE="${POKER_FRONTEND_RUNTIME_FILE:-/etc/nginx/snippets/poker-frontend-runtime.conf}"

echo "[frontend-runtime] prefix=$SSM_PREFIX region=$AWS_REGION out=$OUT_FILE"

RAW_FILE="$(mktemp)"
TMP_FILE="$(mktemp)"
trap 'rm -f "$RAW_FILE" "$TMP_FILE"' EXIT

aws ssm get-parameters-by-path \
    --path "$SSM_PREFIX" \
    --recursive \
    --region "$AWS_REGION" \
    --output json > "$RAW_FILE"

python3 - "$SSM_PREFIX" "$TMP_FILE" "$RAW_FILE" <<'PY'
import json, sys
from urllib.parse import urlparse

prefix, out_path, raw_path = sys.argv[1], sys.argv[2], sys.argv[3]
with open(raw_path) as fh:
    params = json.load(fh).get("Parameters", [])

values = {
    "API_BASE_URL": "",
    "TURNSTILE_SITE_KEY": "",
    "SENTRY_DSN": "",
    "SENTRY_ENV": "production",
    "SENTRY_RELEASE": "",
}
for p in params:
    key = p["Name"][len(prefix):].lstrip("/")
    value = p["Value"].strip("\r\n")
    if "\n" in value or "\r" in value:
        sys.stderr.write(f"ERROR: value for {key} contains an internal newline; refusing.\n")
        sys.exit(1)
    if key in values:
        values[key] = value

# Derive the Sentry CSP report endpoint from the DSN so the enforced CSP can
# report violations. DSN https://<key>@<host>/<project> → report-uri
# https://<host>/api/<project>/security/?sentry_key=<key>.
csp_report = ""
dsn = values["SENTRY_DSN"].strip()
if dsn:
    u = urlparse(dsn)
    key = u.username or ""
    host = u.hostname or ""
    port = f":{u.port}" if u.port else ""
    project = u.path.strip("/").split("/")[-1] if u.path else ""
    if key and host and project:
        csp_report = f"; report-uri {u.scheme}://{host}{port}/api/{project}/security/?sentry_key={key}"

lines = [
    "# AUTO-GENERATED by deploy/fetch-frontend-runtime-from-ssm.sh — source of truth SSM.",
    f'set $poker_api_base       "{values["API_BASE_URL"]}";',
    f'set $poker_turnstile_site_key "{values["TURNSTILE_SITE_KEY"]}";',
    f'set $poker_sentry_dsn     "{values["SENTRY_DSN"]}";',
    f'set $poker_sentry_env     "{values["SENTRY_ENV"]}";',
    f'set $poker_sentry_release "{values["SENTRY_RELEASE"]}";',
    f'set $poker_csp_report     "{csp_report}";',
]
with open(out_path, "w") as fh:
    fh.write("\n".join(lines) + "\n")
PY

if [ -f "$OUT_FILE" ] && cmp -s "$TMP_FILE" "$OUT_FILE"; then
    echo "[frontend-runtime] $OUT_FILE unchanged — no reload needed"
    exit 0
fi

mkdir -p "$(dirname "$OUT_FILE")"
install -m 0644 -o root -g root "$TMP_FILE" "$OUT_FILE"
echo "[frontend-runtime] $OUT_FILE updated"

if ! nginx -t; then
    echo "ERROR: nginx -t failed after writing $OUT_FILE — skipping reload" >&2
    exit 3
fi
systemctl reload nginx
echo "[frontend-runtime] nginx reloaded"
